default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  username: docker
  password: docker

development:
  <<: *default
  database: spotprice_development

production:
  <<: *default
  database: spotprice_development
